apiVersion: apps/v1
kind: Deployment
metadata:
  name: myflaskapp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: myflaskapp
        image: homelybore/demo-flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: my-configmap